[build]
  functions = "functions"
  publish = "frontend/build"

[context.production.environment]
  NODE_VERSION = "14"
  JWT_SECRET = "your_super_secret_jwt_key"
  DATABASE_URL = "file:./dev.db"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
